repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: e0322737dccad136b751416f9e45d9980fe18435 # v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
        args:
          # - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
      - id: terraform_trivy
        args:
          # - --args=--skip-dirs="**/.terraform"
          - --hook-config=--parallelism-limit=1

