name: Static Analysis

on:
  push:

env:
  TAG: "v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0"

jobs:
  static-analysis:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run analysis
        run: |
          docker run -v $(pwd):/lint -w /lint "ghcr.io/antonbabenko/pre-commit-terraform:$TAG" run -a

      - name: Debug
        if: always()
        run: |
          git --no-pager diff
      
